### PR TITLE
[MOVED to #35] BXMSDOC-5389: Draft of "Developing decision services with Kogito"

### PR DESCRIPTION
**Pull request by sterobin**
**Moved to PR #35**

### CODE REVIEW

**Comment by jomarko** [comment]
**Figure 4.27. Adding a new data type**
In the picture there is **Import Data Object** button, however that doesn't exist in kogito world (for now).

**Comment by jomarko** [comment]
I know we discussed formatting/alignment/indentation multiple times, can't we update?
- Example person DRL file using OOPath
- Example person DRL file using traditional notation

Whitespaces seem to me be really wild there.

**Comment by jomarko** [comment]
**Example object method to notify the decision engine that an exam has been moved to a different course**
Last **}** could be at the beginning of the line.

**Comment by jomarko** [comment]
Will we prepare also more lightweight document? more customer scenario oriented? This seem to me like heavy explanation of all features, standards, but miss sample like I want to solve automatic heating turn off/on:
- make diagram like this
- run mvn command like this
- visit url in browser to check changes

**Comment by sterobin** [comment]
@jomarko , thanks. In reply:
* Import data objects: Right, I see that the 0.2.8 tooling release now has the updated DMN designer (with that option removed), so I've just updated all screenshots and pushed, and updated the doc preview.
* Indentation: Right, as we've discussed, this is only wonky in the enterprise doc previews. In the final version on the Portal and in the community ascii-rendered version, the formatting is cleaner.
* Bracket: Right, I've just kept it consistent with the Java code formatter and with the other examples. I realize it could be tidied, but I want to keep all consistent if I can.
* Lightweight example: Right, that's precisely what the "Creating and running your first Kogito app" is for, as you recall. That doc goes through a basic scenario from start to finish using DMN or DRL (with BPMN), from creating the project, designing the DMN asset (or DRL), building the project, and interacting with the generated endpoints to check changes. All as you say. That doc is the lightweight entry point for users, after which users can come to this doc for more details.

**Pull request closed without merging**
